### ISSUE TITLE
不选择图片直接返回，好像会导致crash

### ISSUE THREAD

**Issue by winnel** [ZLYang110/FileSelector#21]
java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.String java.io.File.getAbsolutePath()' on a null object reference
        at com.zlylib.fileselectorlib.ui.FileSelectorActivity.onBackPressed(FileSelectorActivity.java:342)
        at com.zlylib.fileselectorlib.ui.FileSelectorActivity$1.onClick(FileSelectorActivity.java:109)
        at com.zlylib.titlebarlib.ActionBarCommon$3.onClick(ActionBarCommon.java:225)
        at android.view.View.performClick(View.java:7496)
        at android.view.View.performClickInternal(View.java:7473)
        at android.view.View.access$3600(View.java:831)
        at android.view.View$PerformClick.run(View.java:28642)
        at android.os.Handler.handleCallback(Handler.java:938)
        at android.os.Handler.dispatchMessage(Handler.java:99)
        at android.os.Looper.loop(Looper.java:236)
        at android.app.ActivityThread.main(ActivityThread.java:7876)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:656)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:967)

**Comment by winnel** [comment]
问题应该是这样：设置path后setTargetPath("**")，不选择文件返回，会找不到目录

**Comment by ZLYang110** [comment]
好的
